# -*- coding: utf-8 -*-
"""Ecommerce Customers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lewbC2YF4ILK_lOX_S-tJI0I-lccRCYh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Ecommerce Customers.txt')

df.head()

df.shape

df.describe()

df.info()

sns.pairplot(df) #visualisation of total data

df.columns

x= df[['Avg. Session Length', 'Time on App',
       'Time on Website', 'Length of Membership']]

x.head()

y=df['Yearly Amount Spent']

y.head()

#split data intotrain andtest
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

print("x_train size =",x_train.shape)
print("x_test size =",x_test.shape)
print("y_train size =", y_train.shape)
print("y_test size =", y_test.shape)

from sklearn.linear_model import LinearRegression

#call linear regression
lr_model=LinearRegression()

#fit model on the train data
lr_model.fit(x_train,y_train)

#predict value
y_pred=lr_model.predict(x_test)

y_pred

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print("MAE =",mean_absolute_error(y_test,y_pred))
print("MSE =",mean_squared_error(y_test,y_pred))
print("RMSE =",np.sqrt(mean_squared_error(y_test,y_pred)))
print("R Squared Error = " , r2_score(y_test,y_pred))